import { mkdtempSync, writeFileSync, mkdirSync, renameSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const R = new URL('../../../../../', import.meta.url).pathname;
const { startWatchMode } = await import(join(R,'dist/indexer/watcher.js'));
const { resolveConfig } = await import(join(R,'dist/store/config.js'));
const dir = mkdtempSync(join(tmpdir(),'mast-drive-'));
mkdirSync(join(dir,'src')); writeFileSync(join(dir,'src','old.ts'),'export const a=1;\n'); writeFileSync(join(dir,'src','logo.png'),'x'); writeFileSync(join(dir,'src','notes.txt'),'x');
process.env.MAST_STATE_DIR = mkdtempSync(join(tmpdir(),'mast-drive-state-'));
const batches=[]; const ready=Promise.withResolvers();
const h = startWatchMode({ config: resolveConfig({projectRoot:dir}), debounceMs:200, runBatch: async (paths)=>{ batches.push(paths); }, onWarn:(m)=>console.log('warn',m), onReady:()=>ready.resolve() });
await ready.promise;
const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
const step=async(label,fn)=>{ const n=batches.length; fn(); await wait(1500); console.log(label, '->', batches.length>n ? 'batch' : 'no batch'); };
await step('change an existing .ts', ()=>writeFileSync(join(dir,'src','old.ts'),'export const a=2;\n'));
await step('create a new .ts', ()=>writeFileSync(join(dir,'src','new.ts'),'export const b=1;\n'));
await step('change the new .ts', ()=>writeFileSync(join(dir,'src','new.ts'),'export const b=2;\n'));
await step('change a .png', ()=>writeFileSync(join(dir,'src','logo.png'),'y'));
await step('rename notes.txt to notes.md', ()=>renameSync(join(dir,'src','notes.txt'),join(dir,'src','notes.md')));
await step('change notes.md', ()=>writeFileSync(join(dir,'src','notes.md'),'# z\n'));
await step('new directory with a .ts', ()=>{ mkdirSync(join(dir,'lib')); writeFileSync(join(dir,'lib','c.ts'),'export const c=1;\n'); });
await step('change the .ts in the new directory', ()=>writeFileSync(join(dir,'lib','c.ts'),'export const c=2;\n'));
await h.close();
